apiVersion: v1
data:
  POSTGRES_DB: postgres
  POSTGRES_HOSTNAME: db
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  # creationTimestamp: null
  labels:
    io.kompose.service: api-env
  name: env
